/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bootup_v2;

import javax.swing.JOptionPane;

/**
 *
 * @author luigi
 */
public class MenuAluno extends javax.swing.JFrame {
    private final ArquivoIndexado<Aluno> ARQUIVO;
    
    /**
     * Creates new form MenuAluno
     * @throws java.lang.Exception
     */
    public MenuAluno() throws Exception {
        initComponents();
        ARQUIVO = new ArquivoIndexado<>(Aluno.class, "alunos.db", "alunos1.idx", "alunos2.idx");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelBemVindo = new javax.swing.JLabel();
        buttonListar = new javax.swing.JButton();
        buttonIncluir = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonAlterar = new javax.swing.JButton();
        buttonBuscarCodigo = new javax.swing.JButton();
        buttonBuscarNome = new javax.swing.JButton();
        buttonReorganizar = new javax.swing.JButton();
        buttonPovoar = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelBemVindo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBemVindo.setText("Bem vindo(a) à Bootup");

        buttonListar.setText("Listar");
        buttonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListarActionPerformed(evt);
            }
        });

        buttonIncluir.setText("Incluir");
        buttonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncluirActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        buttonAlterar.setText("Alterar");
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        buttonBuscarCodigo.setText("Buscar por Código");
        buttonBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarCodigoActionPerformed(evt);
            }
        });

        buttonBuscarNome.setText("Buscar por Nome");
        buttonBuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarNomeActionPerformed(evt);
            }
        });

        buttonReorganizar.setText("Reorganizar");
        buttonReorganizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReorganizarActionPerformed(evt);
            }
        });

        buttonPovoar.setText("Povoar DB");
        buttonPovoar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPovoarActionPerformed(evt);
            }
        });

        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBemVindo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSair)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buttonIncluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonListar))
                            .addComponent(buttonAlterar)
                            .addComponent(buttonExcluir))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonBuscarNome)
                            .addComponent(buttonBuscarCodigo)
                            .addComponent(buttonReorganizar)
                            .addComponent(buttonPovoar))))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonAlterar, buttonBuscarCodigo, buttonBuscarNome, buttonExcluir, buttonIncluir, buttonListar, buttonPovoar, buttonReorganizar, buttonSair});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonListar)
                    .addComponent(buttonBuscarCodigo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarNome))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAlterar)
                    .addComponent(buttonReorganizar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExcluir)
                    .addComponent(buttonPovoar))
                .addGap(27, 27, 27)
                .addComponent(buttonSair)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonAlterar, buttonBuscarCodigo, buttonBuscarNome, buttonExcluir, buttonIncluir, buttonListar, buttonPovoar, buttonReorganizar, buttonSair});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncluirActionPerformed
        ControleAluno cadastroAluno = new ControleAluno(ARQUIVO, "Inclusão");
        cadastroAluno.setLocationRelativeTo(null);
        cadastroAluno.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastroAluno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonIncluirActionPerformed

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        try {
            // Lendo codigo de aluno a ser alterado.
            String opcao = JOptionPane.showInputDialog(this, "Código", "Alteração", JOptionPane.INFORMATION_MESSAGE);

            if (opcao != null) {
                int codigo = Integer.parseInt(opcao);
                // Aluno a ser alterado.
                Aluno alunoAlterado = (Aluno) ARQUIVO.buscarCodigo(codigo);

                if (codigo <= 0) {
                    JOptionPane.showMessageDialog(this, "Código Inválido!", "Alteração", JOptionPane.INFORMATION_MESSAGE);
                } else if (alunoAlterado == null) {
                    JOptionPane.showMessageDialog(this, "Aluno não encontrado!", "Alteração", JOptionPane.ERROR_MESSAGE);
                } else if (JOptionPane.showConfirmDialog(this, alunoAlterado, "Alteração", JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE) == 0) {

                    // Fazendo alteração.
                    ControleAluno alteracaoAluno = new ControleAluno(ARQUIVO, alunoAlterado, "Alteração");
                    alteracaoAluno.setLocationRelativeTo(null);
                    alteracaoAluno.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    alteracaoAluno.setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Aluno não alterado! :(", "Alteração", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERRO!", "Alteração", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void buttonPovoarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPovoarActionPerformed
        try {
            // Povoando database.
            ARQUIVO.incluir(new Aluno(-1, "Astolfo", "thebarbarian@gmail.com", "grrrrrr", "7070-7070", "55555", "História"));
            ARQUIVO.incluir(new Aluno(-1, "Adenor", "deninho@gmail.com", "idontcare", "8080-8080", "34232", "Música"));
            ARQUIVO.incluir(new Aluno(-1, "Xanaina", "oooohxanaina@gmail.com", "xaxa", "6969-6969", "69696", "Sexologia"));
            ARQUIVO.incluir(new Aluno(-1, "Dollynho", "seuamiguinho@hotmail.com", "guarana", "3483-6753", "00001", "Marketing"));
            ARQUIVO.incluir(new Aluno(-1, "Yudi Presteixo", "presteixo@gmail.com", "jogodavida", "4002-8922", "12325", "Jornalismo"));
            ARQUIVO.incluir(new Aluno(-1, "Lula", "lulapallooza@outlook.com", "lulala", "1313-1313", "13131", "Deretcho"));
            ARQUIVO.incluir(new Aluno(-1, "Temer", "opovonaoebobo@yahoo.com", "foradilmaforalulaforapt", "3171-1713", "15151", "Teatro"));
            ARQUIVO.incluir(new Aluno(-1, "Blond Joseph", "anamaria@gmail.com", "blondjamesblond", "1212-1212", "12121", "Culinária"));
            ARQUIVO.incluir(new Aluno(-1, "Irineu", "vocenaosabe@gmail.com", "nemeu", "0404-0404", "00404", "Filosofia"));
            ARQUIVO.incluir(new Aluno(-1, "Donald Trumpolin", "makeamericagreatagain@cia.us", "lalilulelo", "202456-6213", "49494", "Engenharia Civil"));
            
            JOptionPane.showMessageDialog(this, "Banco de Dados povoado!", "Povoar DB", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERRO!", "Povoar DB", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonPovoarActionPerformed

    private void buttonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListarActionPerformed
        try {
            ListaAlunos listaAlunos = new ListaAlunos(ARQUIVO.listar());
            listaAlunos.setLocationRelativeTo(null);
            listaAlunos.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            listaAlunos.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERRO!", "Listar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonListarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        String opcao = JOptionPane.showInputDialog(this, "Código", "Alteração", JOptionPane.    INFORMATION_MESSAGE);
        
        if (opcao != null) {
            try {
                // Codigo do aluno a ser excluido.
                int codigo = Integer.parseInt(opcao);
                Aluno alunoExcluir = (Aluno) ARQUIVO.buscarCodigo(codigo);
                
                if (codigo <= 0) {
                    JOptionPane.showMessageDialog(this, "Código Inválido!", "Alteração", JOptionPane.INFORMATION_MESSAGE);
                } else if (alunoExcluir == null) {
                    JOptionPane.showMessageDialog(this, "Aluno não encontrado!", "Exclusão", JOptionPane.ERROR_MESSAGE);
                } else if (JOptionPane.showConfirmDialog(this, alunoExcluir, "Exclusão",JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
                    
                    ARQUIVO.excluir(codigo);
                    JOptionPane.showMessageDialog(this, "Aluno excluído! :)", "Exclusão", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Aluno não excluído! :(", "Exclusão", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "ERRO!", "Exclusão", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        dispose();
        
        try {
            MenuPrincipal menu = new MenuPrincipal();
            menu.setLocationRelativeTo(null);
            menu.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            menu.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERRO!", "Menu Principal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarCodigoActionPerformed
        try {
            String opcao = JOptionPane.showInputDialog(this, "Código", "Alteração", JOptionPane.    INFORMATION_MESSAGE);
       
            if (opcao != null) {
                int codigo = Integer.parseInt(opcao);
                Aluno alunoBuscado = (Aluno) ARQUIVO.buscarCodigo(codigo);
                
                if (alunoBuscado != null) {
                    JOptionPane.showMessageDialog(this, alunoBuscado, "Busca por Código", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Aluno não encontrado! :(", "Busca por Código", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERRO!", "Busca por Código", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonBuscarCodigoActionPerformed

    private void buttonBuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarNomeActionPerformed
        try {
            String opcao = JOptionPane.showInputDialog(this, "Nome", "Alteração", JOptionPane.    INFORMATION_MESSAGE);
       
            if (opcao != null) {
                Aluno alunoBuscado = (Aluno) ARQUIVO.buscarString(opcao);
                
                if (alunoBuscado != null) {
                    JOptionPane.showMessageDialog(this, alunoBuscado, "Busca por Código", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Aluno não encontrado! :(", "Busca por Código", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERRO!", "Busca por Código", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonBuscarNomeActionPerformed

    private void buttonReorganizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReorganizarActionPerformed
        try {
            ARQUIVO.reorganizar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERRO!", "Reorganização", JOptionPane.ERROR_MESSAGE);
        }
        JOptionPane.showMessageDialog(this, "Arquivo Reorganizado! :)", "Reorganização", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonReorganizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonBuscarCodigo;
    private javax.swing.JButton buttonBuscarNome;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonIncluir;
    private javax.swing.JButton buttonListar;
    private javax.swing.JButton buttonPovoar;
    private javax.swing.JButton buttonReorganizar;
    private javax.swing.JButton buttonSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBemVindo;
    // End of variables declaration//GEN-END:variables
}
